import type { Metadata } from 'next'
import './globals.css'
import Navbar from '@/components/navbar'
import Sidebar from '@/components/sidebar'

export const metadata: Metadata = {
    title: 'RiffRadar',
    description: 'Generated by create next app',
    icons: {
        icon: '/favicon.ico',
    },
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body>
                <div className="h-full flex flex-col gap-4 p-4">
                    <Navbar />

                    <div className="flex h-full gap-4">
                        <Sidebar />
                        {children}
                    </div>
                </div>
            </body>
        </html>
    )
}
