services:
    nginx:
        image: nginx:latest
        container_name: nginx
        working_dir: /www
        ports:
            - '8000:80'
        volumes:
            - ./docker/config/config.conf:/etc/nginx/conf.d/default.conf
            - ./backend:/var/www/backend:delegated
        depends_on:
            - php
        networks:
            - dev

    php:
        build: ./docker/php/
        container_name: php
        volumes:
            - ./backend:/var/www/backend:delegated
            - ./backend/var:/www/backend/var:delegated
            - ./backend/vendor:/www/backend/vendor:delegated
            - ./docker/php/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini
        depends_on:
            - postgres
        networks:
            - dev

    nextjs:
        build:
            context: .
            dockerfile: docker/nextjs/Dockerfile
        container_name: nextjs
        ports:
            - '3000:3000'
        volumes:
            - ./frontend:/app
            - node_modules:/app/node_modules
        networks:
            - dev
        environment:
            - SYMFONY_URL=http://nginx:80
            - WATCHPACK_POLLING=true
            - CHOKIDAR_USEPOLLING=true

    postgres:
        build: ./docker/postgres/
        container_name: postgres
        ports:
            - '3306:3306'
        volumes:
            - postgres-data:/var/lib/postgres
        networks:
            - dev

    composer_sf:
        build: ./docker/php/
        container_name: composer_sf
        working_dir: /www/backend
        volumes:
            - ./backend:/www/backend
            - ./docker/composer/cache:/tmp/cache
        tty: true
        stdin_open: true
        command: ['bash']
        env_file:
            - ./backend/.env
            - ./backend/.env.local
        depends_on:
            - postgres
            - php
        networks:
            - dev

    mongodb:
        build: ./docker/mongodb/
        container_name: mongodb
        ports:
            - '27017:27017'
        volumes:
            - mongodb-data:/data/db
        networks:
            - dev

volumes:
    postgres-data:
    mongodb-data:
    node_modules:

networks:
    dev:
        driver: bridge
