services:
    nginx:
        image: nginx:latest
        container_name: nginx
        working_dir: /var/www/
        ports:
            - '8000:80'
        volumes:
            - ./docker/config/config.conf:/etc/nginx/conf.d/default.conf
            - ./backend:/var/www/html/backend
        depends_on:
            - php
        networks:
            - dev

    php:
        build: 
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: php
        volumes:
            - ./backend:/var/www/html/backend
            - ./backend/var:/var/www/html/backend/var
            - ./backend/vendor:/var/www/html/backend/vendor
            - ./docker/php/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini
        depends_on:
            - postgres
        networks:
            - dev

    nextjs:
        build:
            context: .
            dockerfile: docker/nextjs/Dockerfile
        container_name: nextjs
        ports:
            - '3000:3000'
        volumes:
            - ./frontend:/var/www/html/frontend
            - node_modules:/var/www/html/frontend/node_modules
        networks:
            - dev
        environment:
            - SYMFONY_URL=http://nginx:80
            - WATCHPACK_POLLING=true
            - CHOKIDAR_USEPOLLING=true

    postgres:
        image: postgres:17.4
        container_name: postgres
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_HOST=${POSTGRES_HOST}
        ports:
            - '5432:5432'
        volumes:
            - postgres-data:/var/lib/postgresql/data
        networks:
            - dev

    mongodb:
        image: mongo:6.0
        container_name: mongodb
        environment:
            - MONGODB_INITDB_ROOT_USERNAME=${MONGODB_INITDB_ROOT_USERNAME}
            - MONGODB_INITDB_ROOT_PASSWORD=${MONGODB_INITDB_ROOT_PASSWORD}
            - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
        ports:
            - '27017:27017'
        volumes:
            - mongodb-data:/data/db
            - mongodb-data:/data/configdb
        networks:
            - dev

volumes:
    postgres-data:
    mongodb-data:
    node_modules:

networks:
    dev:
        driver: bridge
