name: Publish to GHCR

on:
    push:
        branches:
            - main
            - dev
    pull_request:
        branches: [main]

env:
    REGISTRY: ghcr.io

jobs:
    build-and-push-image:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            packages: write
            attestations: write
            id-token: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Image name
              id: image
              run: |
                  IMAGE_NAME="$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')"
                  echo "image_name=$IMAGE_NAME" >> $GITHUB_OUTPUT

            - name: Log in to the Container registry
              uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push Docker image
              id: push
              uses: docker/build-push-action@v6
              with:
                  file: ./docker/php/Dockerfile
                  push: true
                  tags: ${{ env.REGISTRY }}/${{ steps.image.outputs.image_name }}/php:latest
